# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'LCTodayNews' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  pod 'Alamofire', '~> 4.7'
  pod 'SwiftyJSON', '~> 4.0'
  pod 'SnapKit', '~> 4.0.0'
  #pod 'RxSwift',    '~> 4.0'
  pod 'RxCocoa',    '~> 4.0'
  pod 'Nocilla',  :git => 'https://github.com/onevcat/Nocilla.git', :branch => 'swift4'
  pod 'Spring', :git => 'https://github.com/MengTo/Spring.git'
  pod 'Moya/RxSwift', '~> 11.0'
  pod "PromiseKit", "~> 6.0"
  pod "PromiseKit/CoreLocation"
  pod 'MJRefresh'
  pod 'HandyJSON'
# Pods for LCTodayNews

end
